version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      - name: import-shadowing

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-generated: lax
  exclude-rules:
    - linters:
        - lll
      path: api/.*
    - linters:
        - dupl
        - lll
      path: internal/.*
  exclude-dirs:
    - third_party
    - builtin
    - examples
